//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtpFuture.Net {

public class CThostFtdcMarketDataAsk45Field : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcMarketDataAsk45Field(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcMarketDataAsk45Field obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CThostFtdcMarketDataAsk45Field obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CThostFtdcMarketDataAsk45Field() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPFutureApiPINVOKE.delete_CThostFtdcMarketDataAsk45Field(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double AskPrice4 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcMarketDataAsk45Field_AskPrice4_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcMarketDataAsk45Field_AskPrice4_get(swigCPtr);
      return ret;
    } 
  }

  public int AskVolume4 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcMarketDataAsk45Field_AskVolume4_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcMarketDataAsk45Field_AskVolume4_get(swigCPtr);
      return ret;
    } 
  }

  public double AskPrice5 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcMarketDataAsk45Field_AskPrice5_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcMarketDataAsk45Field_AskPrice5_get(swigCPtr);
      return ret;
    } 
  }

  public int AskVolume5 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcMarketDataAsk45Field_AskVolume5_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcMarketDataAsk45Field_AskVolume5_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcMarketDataAsk45Field() : this(CTPFutureApiPINVOKE.new_CThostFtdcMarketDataAsk45Field(), true) {
  }

}

}
