//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtpFuture.Net.Swig {

public class CThostFtdcDepthMarketDataField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcDepthMarketDataField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcDepthMarketDataField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CThostFtdcDepthMarketDataField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CThostFtdcDepthMarketDataField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPFutureApiPINVOKE.delete_CThostFtdcDepthMarketDataField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string TradingDay {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_TradingDay_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_TradingDay_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve1 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_reserve1_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_reserve1_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string reserve2 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_reserve2_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_reserve2_get(swigCPtr);
      return ret;
    } 
  }

  public double LastPrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_LastPrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_LastPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlementPrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_PreSettlementPrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_PreSettlementPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PreClosePrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_PreClosePrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_PreClosePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PreOpenInterest {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_PreOpenInterest_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_PreOpenInterest_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenPrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_OpenPrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_OpenPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double HighestPrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_HighestPrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_HighestPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double LowestPrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_LowestPrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_LowestPrice_get(swigCPtr);
      return ret;
    } 
  }

  public int Volume {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_Volume_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_Volume_get(swigCPtr);
      return ret;
    } 
  }

  public double Turnover {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_Turnover_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_Turnover_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenInterest {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_OpenInterest_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_OpenInterest_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_ClosePrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_ClosePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double SettlementPrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_SettlementPrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_SettlementPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperLimitPrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_UpperLimitPrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_UpperLimitPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double LowerLimitPrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_LowerLimitPrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_LowerLimitPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double PreDelta {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_PreDelta_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_PreDelta_get(swigCPtr);
      return ret;
    } 
  }

  public double CurrDelta {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_CurrDelta_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_CurrDelta_get(swigCPtr);
      return ret;
    } 
  }

  public string UpdateTime {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_UpdateTime_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_UpdateTime_get(swigCPtr);
      return ret;
    } 
  }

  public int UpdateMillisec {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_UpdateMillisec_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_UpdateMillisec_get(swigCPtr);
      return ret;
    } 
  }

  public double BidPrice1 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice1_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice1_get(swigCPtr);
      return ret;
    } 
  }

  public int BidVolume1 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume1_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume1_get(swigCPtr);
      return ret;
    } 
  }

  public double AskPrice1 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice1_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice1_get(swigCPtr);
      return ret;
    } 
  }

  public int AskVolume1 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume1_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume1_get(swigCPtr);
      return ret;
    } 
  }

  public double BidPrice2 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public int BidVolume2 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume2_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume2_get(swigCPtr);
      return ret;
    } 
  }

  public double AskPrice2 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public int AskVolume2 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume2_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume2_get(swigCPtr);
      return ret;
    } 
  }

  public double BidPrice3 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice3_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice3_get(swigCPtr);
      return ret;
    } 
  }

  public int BidVolume3 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume3_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume3_get(swigCPtr);
      return ret;
    } 
  }

  public double AskPrice3 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice3_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice3_get(swigCPtr);
      return ret;
    } 
  }

  public int AskVolume3 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume3_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume3_get(swigCPtr);
      return ret;
    } 
  }

  public double BidPrice4 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice4_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice4_get(swigCPtr);
      return ret;
    } 
  }

  public int BidVolume4 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume4_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume4_get(swigCPtr);
      return ret;
    } 
  }

  public double AskPrice4 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice4_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice4_get(swigCPtr);
      return ret;
    } 
  }

  public int AskVolume4 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume4_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume4_get(swigCPtr);
      return ret;
    } 
  }

  public double BidPrice5 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice5_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidPrice5_get(swigCPtr);
      return ret;
    } 
  }

  public int BidVolume5 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume5_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_BidVolume5_get(swigCPtr);
      return ret;
    } 
  }

  public double AskPrice5 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice5_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskPrice5_get(swigCPtr);
      return ret;
    } 
  }

  public int AskVolume5 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume5_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AskVolume5_get(swigCPtr);
      return ret;
    } 
  }

  public double AveragePrice {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AveragePrice_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_AveragePrice_get(swigCPtr);
      return ret;
    } 
  }

  public string ActionDay {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_ActionDay_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_ActionDay_get(swigCPtr);
      return ret;
    } 
  }

  public string InstrumentID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_InstrumentID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_InstrumentID_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeInstID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_ExchangeInstID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcDepthMarketDataField_ExchangeInstID_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcDepthMarketDataField() : this(CTPFutureApiPINVOKE.new_CThostFtdcDepthMarketDataField(), true) {
  }

}

}
