//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtpFuture.Net {

public class CThostFtdcProductField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcProductField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcProductField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CThostFtdcProductField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CThostFtdcProductField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPFutureApiPINVOKE.delete_CThostFtdcProductField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string ProductID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_ProductID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcProductField_ProductID_get(swigCPtr);
      return ret;
    } 
  }

  public string ProductName {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_ProductName_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcProductField_ProductName_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcProductField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public char ProductClass {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_ProductClass_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcProductField_ProductClass_get(swigCPtr);
      return ret;
    } 
  }

  public int VolumeMultiple {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_VolumeMultiple_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcProductField_VolumeMultiple_get(swigCPtr);
      return ret;
    } 
  }

  public double PriceTick {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_PriceTick_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcProductField_PriceTick_get(swigCPtr);
      return ret;
    } 
  }

  public int MaxMarketOrderVolume {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_MaxMarketOrderVolume_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcProductField_MaxMarketOrderVolume_get(swigCPtr);
      return ret;
    } 
  }

  public int MinMarketOrderVolume {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_MinMarketOrderVolume_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcProductField_MinMarketOrderVolume_get(swigCPtr);
      return ret;
    } 
  }

  public int MaxLimitOrderVolume {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_MaxLimitOrderVolume_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcProductField_MaxLimitOrderVolume_get(swigCPtr);
      return ret;
    } 
  }

  public int MinLimitOrderVolume {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_MinLimitOrderVolume_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcProductField_MinLimitOrderVolume_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionType {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_PositionType_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcProductField_PositionType_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionDateType {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_PositionDateType_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcProductField_PositionDateType_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseDealType {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_CloseDealType_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcProductField_CloseDealType_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeCurrencyID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_TradeCurrencyID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcProductField_TradeCurrencyID_get(swigCPtr);
      return ret;
    } 
  }

  public char MortgageFundUseRange {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_MortgageFundUseRange_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcProductField_MortgageFundUseRange_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeProductID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_ExchangeProductID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcProductField_ExchangeProductID_get(swigCPtr);
      return ret;
    } 
  }

  public double UnderlyingMultiple {
    set {
      CTPFutureApiPINVOKE.CThostFtdcProductField_UnderlyingMultiple_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcProductField_UnderlyingMultiple_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcProductField() : this(CTPFutureApiPINVOKE.new_CThostFtdcProductField(), true) {
  }

}

}
