//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtpFuture.Net {

public class CThostFtdcAccountPropertyField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcAccountPropertyField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcAccountPropertyField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CThostFtdcAccountPropertyField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CThostFtdcAccountPropertyField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPFutureApiPINVOKE.delete_CThostFtdcAccountPropertyField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string BrokerID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_AccountID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_AccountID_get(swigCPtr);
      return ret;
    } 
  }

  public string BankID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_BankID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_BankID_get(swigCPtr);
      return ret;
    } 
  }

  public string BankAccount {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_BankAccount_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_BankAccount_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenName {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OpenName_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OpenName_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenBank {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OpenBank_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OpenBank_get(swigCPtr);
      return ret;
    } 
  }

  public int IsActive {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_IsActive_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_IsActive_get(swigCPtr);
      return ret;
    } 
  }

  public char AccountSourceType {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_AccountSourceType_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_AccountSourceType_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenDate {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OpenDate_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OpenDate_get(swigCPtr);
      return ret;
    } 
  }

  public string CancelDate {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_CancelDate_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_CancelDate_get(swigCPtr);
      return ret;
    } 
  }

  public string OperatorID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OperatorID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OperatorID_get(swigCPtr);
      return ret;
    } 
  }

  public string OperateDate {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OperateDate_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OperateDate_get(swigCPtr);
      return ret;
    } 
  }

  public string OperateTime {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OperateTime_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_OperateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_CurrencyID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcAccountPropertyField_CurrencyID_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcAccountPropertyField() : this(CTPFutureApiPINVOKE.new_CThostFtdcAccountPropertyField(), true) {
  }

}

}
