//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtpFuture.Net.Swig {

public class CThostFtdcInvestorProductGroupMarginField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcInvestorProductGroupMarginField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcInvestorProductGroupMarginField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CThostFtdcInvestorProductGroupMarginField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CThostFtdcInvestorProductGroupMarginField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPFutureApiPINVOKE.delete_CThostFtdcInvestorProductGroupMarginField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string reserve1 {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_reserve1_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_reserve1_get(swigCPtr);
      return ret;
    } 
  }

  public string BrokerID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestorID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_InvestorID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_InvestorID_get(swigCPtr);
      return ret;
    } 
  }

  public string TradingDay {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_TradingDay_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_TradingDay_get(swigCPtr);
      return ret;
    } 
  }

  public int SettlementID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_SettlementID_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_SettlementID_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_FrozenMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_FrozenMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double LongFrozenMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongFrozenMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongFrozenMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ShortFrozenMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortFrozenMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortFrozenMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UseMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_UseMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_UseMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double LongUseMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongUseMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongUseMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ShortUseMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortUseMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortUseMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double LongExchMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ShortExchMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortExchMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortExchMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenCommission {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_FrozenCommission_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_FrozenCommission_get(swigCPtr);
      return ret;
    } 
  }

  public double Commission {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_Commission_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_Commission_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenCash {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_FrozenCash_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_FrozenCash_get(swigCPtr);
      return ret;
    } 
  }

  public double CashIn {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_CashIn_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_CashIn_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double OffsetAmount {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_OffsetAmount_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_OffsetAmount_get(swigCPtr);
      return ret;
    } 
  }

  public double LongOffsetAmount {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongOffsetAmount_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongOffsetAmount_get(swigCPtr);
      return ret;
    } 
  }

  public double ShortOffsetAmount {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortOffsetAmount_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortOffsetAmount_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchOffsetAmount {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ExchOffsetAmount_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ExchOffsetAmount_get(swigCPtr);
      return ret;
    } 
  }

  public double LongExchOffsetAmount {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongExchOffsetAmount_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_LongExchOffsetAmount_get(swigCPtr);
      return ret;
    } 
  }

  public double ShortExchOffsetAmount {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortExchOffsetAmount_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ShortExchOffsetAmount_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ExchangeID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ExchangeID_get(swigCPtr);
      return ret;
    } 
  }

  public string InvestUnitID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_InvestUnitID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_InvestUnitID_get(swigCPtr);
      return ret;
    } 
  }

  public string ProductGroupID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ProductGroupID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcInvestorProductGroupMarginField_ProductGroupID_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcInvestorProductGroupMarginField() : this(CTPFutureApiPINVOKE.new_CThostFtdcInvestorProductGroupMarginField(), true) {
  }

}

}
