//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtpFuture.Net {

public class CThostFtdcReqUserLoginWithTextField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcReqUserLoginWithTextField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcReqUserLoginWithTextField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CThostFtdcReqUserLoginWithTextField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CThostFtdcReqUserLoginWithTextField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPFutureApiPINVOKE.delete_CThostFtdcReqUserLoginWithTextField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string TradingDay {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_TradingDay_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_TradingDay_get(swigCPtr);
      return ret;
    } 
  }

  public string BrokerID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string UserID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_UserID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_UserID_get(swigCPtr);
      return ret;
    } 
  }

  public string Password {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_Password_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_Password_get(swigCPtr);
      return ret;
    } 
  }

  public string UserProductInfo {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_UserProductInfo_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_UserProductInfo_get(swigCPtr);
      return ret;
    } 
  }

  public string InterfaceProductInfo {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_InterfaceProductInfo_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_InterfaceProductInfo_get(swigCPtr);
      return ret;
    } 
  }

  public string ProtocolInfo {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_ProtocolInfo_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_ProtocolInfo_get(swigCPtr);
      return ret;
    } 
  }

  public string MacAddress {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_MacAddress_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_MacAddress_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientIPAddress {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_ClientIPAddress_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_ClientIPAddress_get(swigCPtr);
      return ret;
    } 
  }

  public string LoginRemark {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_LoginRemark_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_LoginRemark_get(swigCPtr);
      return ret;
    } 
  }

  public string Text {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_Text_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_Text_get(swigCPtr);
      return ret;
    } 
  }

  public int ClientIPPort {
    set {
      CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_ClientIPPort_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcReqUserLoginWithTextField_ClientIPPort_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcReqUserLoginWithTextField() : this(CTPFutureApiPINVOKE.new_CThostFtdcReqUserLoginWithTextField(), true) {
  }

}

}
