//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtpFuture.Net.Swig {

public class CThostFtdcTradingAccountField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcTradingAccountField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcTradingAccountField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CThostFtdcTradingAccountField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CThostFtdcTradingAccountField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPFutureApiPINVOKE.delete_CThostFtdcTradingAccountField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string BrokerID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_BrokerID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_BrokerID_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_AccountID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_AccountID_get(swigCPtr);
      return ret;
    } 
  }

  public double PreMortgage {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreMortgage_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreMortgage_get(swigCPtr);
      return ret;
    } 
  }

  public double PreCredit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreCredit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreCredit_get(swigCPtr);
      return ret;
    } 
  }

  public double PreDeposit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreDeposit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreDeposit_get(swigCPtr);
      return ret;
    } 
  }

  public double PreBalance {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreBalance_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double PreMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double InterestBase {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_InterestBase_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_InterestBase_get(swigCPtr);
      return ret;
    } 
  }

  public double Interest {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Interest_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Interest_get(swigCPtr);
      return ret;
    } 
  }

  public double Deposit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Deposit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Deposit_get(swigCPtr);
      return ret;
    } 
  }

  public double Withdraw {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Withdraw_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Withdraw_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FrozenMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FrozenMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenCash {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FrozenCash_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FrozenCash_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenCommission {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FrozenCommission_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FrozenCommission_get(swigCPtr);
      return ret;
    } 
  }

  public double CurrMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_CurrMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_CurrMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double CashIn {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_CashIn_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_CashIn_get(swigCPtr);
      return ret;
    } 
  }

  public double Commission {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Commission_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Commission_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double Balance {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Balance_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Balance_get(swigCPtr);
      return ret;
    } 
  }

  public double Available {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Available_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Available_get(swigCPtr);
      return ret;
    } 
  }

  public double WithdrawQuota {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_WithdrawQuota_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_WithdrawQuota_get(swigCPtr);
      return ret;
    } 
  }

  public double Reserve {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Reserve_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Reserve_get(swigCPtr);
      return ret;
    } 
  }

  public string TradingDay {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_TradingDay_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_TradingDay_get(swigCPtr);
      return ret;
    } 
  }

  public int SettlementID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SettlementID_set(swigCPtr, value);
    } 
    get {
      int ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SettlementID_get(swigCPtr);
      return ret;
    } 
  }

  public double Credit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Credit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Credit_get(swigCPtr);
      return ret;
    } 
  }

  public double Mortgage {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Mortgage_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_Mortgage_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchangeMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_ExchangeMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_ExchangeMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double DeliveryMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_DeliveryMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_DeliveryMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchangeDeliveryMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_ExchangeDeliveryMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_ExchangeDeliveryMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ReserveBalance {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_ReserveBalance_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_ReserveBalance_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyID {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_CurrencyID_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_CurrencyID_get(swigCPtr);
      return ret;
    } 
  }

  public double PreFundMortgageIn {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreFundMortgageIn_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreFundMortgageIn_get(swigCPtr);
      return ret;
    } 
  }

  public double PreFundMortgageOut {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreFundMortgageOut_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_PreFundMortgageOut_get(swigCPtr);
      return ret;
    } 
  }

  public double FundMortgageIn {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FundMortgageIn_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FundMortgageIn_get(swigCPtr);
      return ret;
    } 
  }

  public double FundMortgageOut {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FundMortgageOut_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FundMortgageOut_get(swigCPtr);
      return ret;
    } 
  }

  public double FundMortgageAvailable {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FundMortgageAvailable_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FundMortgageAvailable_get(swigCPtr);
      return ret;
    } 
  }

  public double MortgageableFund {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_MortgageableFund_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_MortgageableFund_get(swigCPtr);
      return ret;
    } 
  }

  public double SpecProductMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SpecProductFrozenMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductFrozenMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductFrozenMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SpecProductCommission {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductCommission_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductCommission_get(swigCPtr);
      return ret;
    } 
  }

  public double SpecProductFrozenCommission {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductFrozenCommission_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductFrozenCommission_get(swigCPtr);
      return ret;
    } 
  }

  public double SpecProductPositionProfit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductPositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductPositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double SpecProductCloseProfit {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductCloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductCloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double SpecProductPositionProfitByAlg {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductPositionProfitByAlg_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductPositionProfitByAlg_get(swigCPtr);
      return ret;
    } 
  }

  public double SpecProductExchangeMargin {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductExchangeMargin_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_SpecProductExchangeMargin_get(swigCPtr);
      return ret;
    } 
  }

  public char BizType {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_BizType_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_BizType_get(swigCPtr);
      return ret;
    } 
  }

  public double FrozenSwap {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FrozenSwap_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_FrozenSwap_get(swigCPtr);
      return ret;
    } 
  }

  public double RemainSwap {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_RemainSwap_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTradingAccountField_RemainSwap_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcTradingAccountField() : this(CTPFutureApiPINVOKE.new_CThostFtdcTradingAccountField(), true) {
  }

}

}
