//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtpFuture.Net.Swig {

public class CThostFtdcTransferBankToFutureReqField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CThostFtdcTransferBankToFutureReqField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CThostFtdcTransferBankToFutureReqField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CThostFtdcTransferBankToFutureReqField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CThostFtdcTransferBankToFutureReqField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CTPFutureApiPINVOKE.delete_CThostFtdcTransferBankToFutureReqField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string FutureAccount {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_FutureAccount_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_FutureAccount_get(swigCPtr);
      return ret;
    } 
  }

  public char FuturePwdFlag {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_FuturePwdFlag_set(swigCPtr, value);
    } 
    get {
      char ret = CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_FuturePwdFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string FutureAccPwd {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_FutureAccPwd_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_FutureAccPwd_get(swigCPtr);
      return ret;
    } 
  }

  public double TradeAmt {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_TradeAmt_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_TradeAmt_get(swigCPtr);
      return ret;
    } 
  }

  public double CustFee {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_CustFee_set(swigCPtr, value);
    } 
    get {
      double ret = CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_CustFee_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyCode {
    set {
      CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_CurrencyCode_set(swigCPtr, value);
    } 
    get {
      string ret = CTPFutureApiPINVOKE.CThostFtdcTransferBankToFutureReqField_CurrencyCode_get(swigCPtr);
      return ret;
    } 
  }

  public CThostFtdcTransferBankToFutureReqField() : this(CTPFutureApiPINVOKE.new_CThostFtdcTransferBankToFutureReqField(), true) {
  }

}

}
